FROM nginx:alpine

# Crear carpeta /mf0223 y copiar archivos ahí
RUN mkdir -p /usr/share/nginx/html/mf0223
COPY index.html /usr/share/nginx/html/mf0223/
COPY styles.css /usr/share/nginx/html/mf0223/
COPY script.js /usr/share/nginx/html/mf0223/

EXPOSE 80

